/*****************************************************************************
 * Copyright (c) 2010 CEA LIST.
 *    
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *  Camille Letavernier (CEA LIST) camille.letavernier@cea.fr - Initial API and implementation
 *****************************************************************************/
package org.eclipse.papyrus.infra.xtext.widgets.adapter;

import org.eclipse.emf.ecore.EObject;

import com.google.inject.Injector;


public interface IXtextAdapter {

	/**
	 * In some cases, the Xtext object is different from the model object
	 * This method is called when the modifications on the Xtext model are
	 * validated
	 * 
	 * @param xtextObject
	 *        The EObject generated by the compilation of the Xtext model
	 * @param sourceModelObject
	 *        The current value for the reference being edited
	 * @return the Model object
	 *         The new value for the reference being edited
	 */
	public EObject reconcile(EObject sourceModelObject, EObject xtextObject);

	/**
	 * Returns the Xtext String representing the given EObject
	 * 
	 * @param modelObject
	 *        The EObject being edited. May be null if the reference is unset.
	 * @return
	 *         The Xtext String representing the given EObject
	 */
	public String getText(EObject modelObject);

	/**
	 * @return the Injector to initialize the Xtext editor
	 */
	public Injector getInjector();
}
