/*
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.textedit.common.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UmlCommonUiModule extends org.eclipse.papyrus.uml.textedit.common.xtext.ui.AbstractUmlCommonUiModule {

	public UmlCommonUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
