/*
* generated by Xtext
*/
package org.eclipse.papyrus.uml.textedit.state.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class UmlStateOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
