<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="extensions" nsURI="http://www.eclipse.org/emf/compare/papyrus"
    nsPrefix="papyruscompare">
  <eClassifiers xsi:type="ecore:EClass" name="PapyrusDiff" abstract="true" eSuperTypes="../../org.eclipse.emf.compare/model/compare.ecore#//Diff"/>
  <eClassifiers xsi:type="ecore:EClass" name="PapyrusGeneralizationChange" eSuperTypes="#//PapyrusDiff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalizationChange" eType="ecore:EClass ../../org.eclipse.emf.compare/model/compare.ecore#//ReferenceChange"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritedFeatureNodeChange"
        eType="ecore:EClass ../../org.eclipse.emf.compare.diagram/model/diagramCompare.ecore#//NodeChange"/>
  </eClassifiers>
</ecore:EPackage>
