<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nattable" nsURI="http://www.eclipse.org/papyrus/nattable/model"
    nsPrefix="nattable">
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//nattableconfiguration/TableNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableConfiguration" lowerBound="1"
        eType="#//nattableconfiguration/TableConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invertAxis" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnAxisProvidersHistory"
        lowerBound="1" upperBound="-1" eType="#//nattableaxisprovider/AbstractAxisProvider"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rowAxisProvidersHistory"
        lowerBound="1" upperBound="-1" eType="#//nattableaxisprovider/AbstractAxisProvider"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localRowAxisConfiguration"
        eType="#//LocalTableAxisConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localColumnAxisConfiguration"
        eType="#//LocalTableAxisConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentRowAxisProvider"
        lowerBound="1" eType="#//nattableaxisprovider/AbstractAxisProvider"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentColumnAxisManager"
        lowerBound="1" eType="#//nattableaxisprovider/AbstractAxisProvider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAxis" abstract="true" interface="true"
      eSuperTypes="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
    <eOperations name="getElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eOperations name="getLocalLabelConfiguration" eType="#//nattablelabelprovider/AbstractLabelConfiguration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdAxis" abstract="true" eSuperTypes="#//IAxis">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="element" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectAxis" eSuperTypes="#//ObjectAxis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MasterAxisProvider" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pastedElementContainmentFeature"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlaveAxisProvider" interface="true"
      eSuperTypes="#//AxisProvider"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableAxisConfiguration" eSuperTypes="#//nattableaxisconfiguration/AbstractAxisConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="axisManagers" lowerBound="1"
        upperBound="-1" eType="#//AxisManager" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AxisManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelConfiguration" lowerBound="1"
        eType="#//nattablelabelprovider/AbstractLabelConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaAxisManagerId" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronizedAxisProvider" eSuperTypes="#//AxisProvider"/>
  <eClassifiers xsi:type="ecore:EClass" name="AxisProvider" eSuperTypes="#//nattableaxisprovider/AbstractAxisProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="axis" upperBound="-1" eType="#//IAxis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureAxis" abstract="true" eSuperTypes="#//SlaveAxisProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="localLabelConfiguration"
        eType="#//nattablelabelprovider/FeatureLabelProviderConfiguration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectAxis" abstract="true" eSuperTypes="#//IAxis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="localLabelConfiguration"
        eType="#//nattablelabelprovider/ObjectLabelProviderConfiguration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureIdAxis" eSuperTypes="#//IdAxis #//FeatureAxis"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMFFeatureAxis" eSuperTypes="#//FeatureAxis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectIdAxis" eSuperTypes="#//IdAxis #//ObjectAxis"/>
  <eClassifiers xsi:type="ecore:EClass" name="AxisManagerConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="localLabelConfiguration"
        eType="#//nattablelabelprovider/AbstractLabelConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaAxisManagerId" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalTableAxisConfiguration" eSuperTypes="#//nattableaxisconfiguration/AbstractAxisConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="axisManagerConfigurations"
        upperBound="-1" eType="#//AxisManagerConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureAxisManager" eSuperTypes="#//AxisManager">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showOnlyCommonFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureAxisManagerConfiguration" eSuperTypes="#//AxisManagerConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showOnlyCommonFeature"/>
  </eClassifiers>
  <eSubpackages name="nattableconfiguration" nsURI="http://www.eclipse.org/papyrus/nattable/model/nattableconfiguration"
      nsPrefix="nattableconfiguration">
    <eClassifiers xsi:type="ecore:EClass" name="TableNamedElement" abstract="true"
        eSuperTypes="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TableConfiguration" eSuperTypes="#//nattableconfiguration/TableNamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconPath" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="creationTester" eType="#//nattabletester/AbstractTableTester"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cellEditorDeclaration"
          lowerBound="1" eType="#//nattableconfiguration/CellEditorDeclaration" defaultValueLiteral="COLUMN"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rowAxisConfiguration"
          lowerBound="1" eType="#//TableAxisConfiguration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="columnAxisConfiguration"
          lowerBound="1" eType="#//TableAxisConfiguration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="columnAxisProviders"
          lowerBound="1" upperBound="-1" eType="#//nattableaxisprovider/AbstractAxisProvider"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rowAxisProviders" lowerBound="1"
          upperBound="-1" eType="#//nattableaxisprovider/AbstractAxisProvider" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultRowAxisProvider"
          lowerBound="1" eType="#//nattableaxisprovider/AbstractAxisProvider"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultColumnAxisProvider"
          eType="#//nattableaxisprovider/AbstractAxisProvider"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CellEditorDeclaration">
      <eLiterals name="COLUMN"/>
      <eLiterals name="ROW" value="1"/>
      <eLiterals name="CELL" value="2"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="nattableaxisprovider" nsURI="http://www.eclipse.org/papyrus/nattable/model/table/nattableaxisprovider"
      nsPrefix="nattableaxisprovider">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractAxisProvider" abstract="true"
        interface="true" eSuperTypes="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement #//nattableconfiguration/TableNamedElement">
      <eOperations name="getAxis" upperBound="-1" eType="#//IAxis"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DefaultAxisProvider" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="EMFFeatureValueAxisProvider" eSuperTypes="#//MasterAxisProvider #//SynchronizedAxisProvider">
      <eStructuralFeatures xsi:type="ecore:EReference" name="listenFeature" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="nattablelabelprovider" nsURI="http://www.eclipse.org/papyrus/nattable/model/table/nattablecontentprovider"
      nsPrefix="nattablelabelprovider">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractLabelConfiguration" abstract="true"
        eSuperTypes="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelProviderContext"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureLabelProviderConfiguration"
        eSuperTypes="#//nattablelabelprovider/ObjectLabelProviderConfiguration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayIsDerived" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayType" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayMultiplicity"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectLabelProviderConfiguration"
        eSuperTypes="#//nattablelabelprovider/AbstractLabelConfiguration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayIcon" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayLabel" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="nattableaxisconfiguration" nsURI="http://www.eclipse.org/papyrus/nattable/model/table/nattableaxisconfiguration"
      nsPrefix="nattableaxisconfiguration">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractAxisConfiguration" abstract="true"
        eSuperTypes="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLabelConfiguration"
          upperBound="-1" eType="#//nattablelabelprovider/AbstractLabelConfiguration"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexStyle" lowerBound="1"
          eType="#//nattableaxisconfiguration/AxisIndexStyle"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayLabel" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayFilter" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayIndex" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DefaultAxisConfiguration"/>
    <eClassifiers xsi:type="ecore:EEnum" name="AxisIndexStyle">
      <eLiterals name="NUMERIC" literal="NUMERIC"/>
      <eLiterals name="ALPHABETIC" value="1" literal="ALPHABETIC"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="nattabletester" nsURI="http://www.eclipse.org/papyrus/nattable/model/table/nattabletester"
      nsPrefix="nattabletester">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractTableTester" abstract="true"
        eSuperTypes="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
      <eOperations name="getTester" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JavaTableTester" eSuperTypes="#//nattabletester/AbstractTableTester">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tester" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
