/*
 * generated by Xtext
 */
package org.eclipse.papyrus.message.editor.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UmlMessageUiModule extends org.eclipse.papyrus.message.editor.xtext.ui.AbstractUmlMessageUiModule {
	public UmlMessageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
