<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="profileefacet" nsURI="http://www.eclipse.org/papyrus/0.9/profileefacet"
    nsPrefix="profileefacet">
  <eClassifiers xsi:type="ecore:EClass" name="ProfileFacetSet" eSuperTypes="platform:/plugin/org.eclipse.emf.facet.efacet.metamodel/model/efacet-0.2.0.ecore#//FacetSet #//EObjectFacetRepresentation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="a 'ProfileFacetSet' is used to represent a UML Profile"/>
    </eAnnotations>
    <eOperations name="getOwnedProfileFacetSets" upperBound="-1" eType="#//ProfileFacetSet">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="returns the ProfileFacetSet aggregated by this ProfileFacetSet"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getStereotypeFacets" upperBound="-1" eType="#//StereotypeFacet">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="returns the StereotypeFacets owned by this ProfileFacetSet"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profileQualifiedName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the qualified name of the represented profile"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StereotypeFacet" eSuperTypes="platform:/plugin/org.eclipse.emf.facet.efacet.metamodel/model/efacet-0.2.0.ecore#//Facet #//EObjectFacetRepresentation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="a 'StereotypeFacet' is used to represent a UML Stereotype"/>
    </eAnnotations>
    <eOperations name="getStereotypePropertyElements" upperBound="-1" eType="#//StereotypePropertyElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="returns the StereotypePropertyelement owned by this StereotypeFacet"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotypeQualifiedName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the qualified name of the represented stereotype"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StereotypePropertyElement" abstract="true"
      eSuperTypes="platform:/plugin/org.eclipse.emf.facet.efacet.metamodel/model/efacet-0.2.0.ecore#//FacetElement #//EObjectFacetRepresentation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="the abstract type used to represent the properties of the stereotype"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the name of the represented property of stereotype"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDerived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="indicates if the property is Derived. This property will probably used by a customization on the header of the columns (to add a '/' to the name column). &#xD;&#xA;We need it because if we have columns representing a stereotype property and if the concerning profile is not applied on the model, we won' be able to refind the real &#xD;&#xA;property to know if this property is derived or not."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StereotypePropertyFacetReference" eSuperTypes="platform:/plugin/org.eclipse.emf.facet.efacet.metamodel/model/efacet-0.2.0.ecore#//FacetReference #//StereotypePropertyElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="a 'StereotypePropertyFacetReference is used to represent a property typed by an EObject"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StereotypePropertyFacetAttribute" eSuperTypes="platform:/plugin/org.eclipse.emf.facet.efacet.metamodel/model/efacet-0.2.0.ecore#//FacetAttribute #//StereotypePropertyElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="a 'StereotypePropertyFacetReference is used to represent a property typed by a DataType, a PrimitiveType or an Enumeration"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectFacetRepresentation" abstract="true"
      interface="true" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This element is used to store the XMI_ID of the represented element."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="represented_element_xmi_id"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The XMI_ID of the represented element."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
