<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="papyrustable" nsURI="http://www.eclipse.org/Papyrus/PapyrusTable/0.9.0/papyrustable"
    nsPrefix="papyrustable">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="This package contains the model used to store the Papyrus Table."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PapyrusTable" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This element represents the tables used in Papyrus."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This field allows to store a name for the Papyrus Table."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This field allows to store the type of the Papyrus Table. It is used to know how &#xD;&#xA;to open it in the papyrus sasheditor."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" eType="ecore:EClass platform:/plugin/org.eclipse.emf.facet.widgets.table.metamodel/model/table-0.2.0.ecore#//Table"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This field reference the EMF-Facet table that we use for the papyrus Table.&#xD;&#xA;We choose to reference it (and not to do an inheritance) in order to be sure&#xD;&#xA;to respect their API."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillingMode" eType="#//FillingMode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@deprecated : You shoudl use the enumeration provided by PapyrusTableConfiguration&#xD;&#xA;This enumeration provides literals representing the ways to fill the table."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillMode" eType="ecore:EEnum platform:/plugin/org.eclipse.papyrus.infra.table.efacet.papyrustableconfiguration.metamodel/model/papyrustableconfiguration.ecore#//FillMode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This attribute allows to store how the table should be filled."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextFeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This field references the EStructuralFeature to listen when the table is in Feature Mode."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queries" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.facet.efacet.metamodel/model/efacet-0.2.0.ecore#//extensible/Query">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This field references the queries used to fill table when the table is in queries mode."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usingUser" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This attribute is true when fillingMode==User."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usingContextFeature" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This attribute is true when fillingMode==Feature."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usingQueries" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This attribute is true when fillingMode==Queries."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pastedElementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This attribute stores the id of the element represented by the row during a paste action in the table."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pasteElementContainementFeature"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This property reference the feature of the context of the table which is used as containement feature&#xD;&#xA;for the pasted elements."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="papyrusTableConfiguration"
        eType="ecore:EClass platform:/plugin/org.eclipse.papyrus.infra.table.efacet.papyrustableconfiguration.metamodel/model/papyrustableconfiguration.ecore#//PapyrusTableConfiguration">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This property references the initial PapyrusTableConfiguration used to create this table."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FillingMode">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@deprecated : You shoudl use the enumeration provided by PapyrusTableConfiguration&#xD;&#xA;This enumeration provides literals representing the ways to fill the table."/>
    </eAnnotations>
    <eLiterals name="User" literal="USER">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This user drops the elements to fill the table."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Queries" value="1" literal="QUERIES">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="We use queries to fill the table."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ContextFeature" value="2" literal="CONTEXT_FEATURE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="We listen a feature of the context of the table to fill it."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
</ecore:EPackage>
