<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PapyrusTableConfiguration" nsURI="http://www.eclipse.org/PapyrusTableInstance/0.9.1/papyrustableconfiguration"
    nsPrefix="PapyrusTableConfiguration">
  <eClassifiers xsi:type="ecore:EClass" name="PapyrusTableConfiguration" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pastedElementContainmentFeature"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pastedElementId" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TableConfiguration" eType="ecore:EClass platform:/plugin/org.eclipse.emf.facet.widgets.nattable.tableconfiguration/model/tableConfiguration2.ecore#//TableConfiguration2"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
