<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="di2"
    nsPrefix="di2">
  <eClassifiers xsi:type="ecore:EClass" name="DiagramElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isVisble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" upperBound="-1"
        eType="#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//GraphElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphElement" eSuperTypes="#//DiagramElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contained" upperBound="-1"
        eType="#//DiagramElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" upperBound="-1" eType="#//DiagramLink"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticModel" eType="#//SemanticModelBridge"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="#//Point"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphEdgeSource" upperBound="-1"
        eType="#//GraphEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphEdgeTarget" upperBound="-1"
        eType="#//GraphEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//DiagramElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isIndividualRepresentation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenced" lowerBound="1"
        eType="#//DiagramElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphEdge" eSuperTypes="#//GraphElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anchorSource" lowerBound="1"
        eType="#//GraphElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anchorTarget" lowerBound="1"
        eType="#//GraphElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waypoints" upperBound="-1"
        eType="#//Point"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphNode" eSuperTypes="#//GraphElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="#//Dimension"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="#//Diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zoom" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewport" eType="#//Point"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphElement" lowerBound="1"
        eType="#//GraphElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" eSuperTypes="#//GraphNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//SemanticModelBridge"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zoom" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewport" eType="#//Point"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramLink" upperBound="-1"
        eType="#//DiagramLink"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TypeDiagram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticModelBridge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="presentation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphElement" eType="#//GraphElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleSemanticModelElement" eSuperTypes="#//SemanticModelBridge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeinfo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Uml1SemanticModelBridge" eSuperTypes="#//SemanticModelBridge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreSemanticModelBridge" eSuperTypes="#//SemanticModelBridge"/>
  <eClassifiers xsi:type="ecore:EClass" name="LeafElement" eSuperTypes="#//DiagramElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextElement" eSuperTypes="#//LeafElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//LeafElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphicPrimitive" eSuperTypes="#//LeafElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Polilyne" eSuperTypes="#//GraphicPrimitive">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waypoints" lowerBound="2"
        upperBound="-1" eType="#//Point"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="closed" lowerBound="2"
        upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ellipse" eSuperTypes="#//GraphicPrimitive">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="center" eType="#//Point"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radiusX" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radiusY" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rotation" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startAngle" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endAngle" eType="#//Double"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Point" instanceClassName="org.eclipse.draw2d.geometry.Point"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dimension" instanceClassName="org.eclipse.draw2d.geometry.Dimension"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Double" instanceClassName="double"/>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeDiagram" instanceClassName="">
    <eLiterals name="ClassDiagram" value="1"/>
    <eLiterals name="CompositeStructureDiagram" value="2"/>
    <eLiterals name="ComponentDiagram" value="3"/>
    <eLiterals name="DeploymentDiagram" value="4"/>
    <eLiterals name="ObjectDiagram" value="5"/>
    <eLiterals name="PackageDiagram" value="6"/>
    <eLiterals name="ActivityDiagram" value="7"/>
    <eLiterals name="SequenceDiagram" value="8"/>
    <eLiterals name="CommunicationDiagram" value="9"/>
    <eLiterals name="InteractionOverviewDiagram" value="10"/>
    <eLiterals name="TimingDiagram" value="11"/>
    <eLiterals name="UseCaseDiagram" value="12"/>
    <eLiterals name="StateMachineDiagram" value="13"/>
  </eClassifiers>
</ecore:EPackage>
