/*
 * generated by Xtext
 */
package org.eclipse.papyrus.transition.editor.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UmlTransitionUiModule extends org.eclipse.papyrus.transition.editor.xtext.ui.AbstractUmlTransitionUiModule {
	public UmlTransitionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
