<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="">
  <eClassifiers xsi:type="ecore:EClass" name="pTable">
    <eOperations name="getLines"/>
    <eOperations name="getRows"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pTableConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pastedElementId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pastedElementContainmentFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context or the same name as the diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rowContentProvider" eType="#//DataProvider"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnContentProvider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataProvider" abstract="true">
    <eOperations name="getData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VolatileDataProvider" eSuperTypes="#//DataProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" volatile="true"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SerializedDataProvider" eSuperTypes="#//DataProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="canBePresentedInTheTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureDataProvider" eSuperTypes="#//VolatileDataProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryDataProvider" eSuperTypes="#//VolatileDataProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fillingQueries" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell">
    <eOperations name="setPastedValue">
      <eParameters name="pastedText" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unresolvedPastedText" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundColor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column" eSuperTypes="#//Line">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sortState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sorter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundColor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Row" eSuperTypes="#//Line"/>
</ecore:EPackage>
