/*
 * generated by Xtext
 */
package org.eclipse.papyrus.stereotypeapplicationwithvsl.editor.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StereotypeApplicationWithVSLRuntimeModule extends org.eclipse.papyrus.stereotypeapplicationwithvsl.editor.xtext.AbstractStereotypeApplicationWithVSLRuntimeModule {

}
