/*
* generated by Xtext
*/
package org.eclipse.papyrus.message.editor.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class UmlMessageOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
