// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define TestCDTintegration_Class2_BODY

/************************************************************
              Class2 class body
 ************************************************************/



// include associated header file
#include <TestCDTintegration/Class2.h>



// Derived includes directives



// static attributes (if any)




/************************************************************
              End of Class2 class body
 ************************************************************/