// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef TESTCDTINTEGRATION_CLASS3_H
#define TESTCDTINTEGRATION_CLASS3_H

/************************************************************
              Class3 class header
 ************************************************************/

/* Owner package header include                             */
#include <TestCDTintegration/Pkg_TestCDTintegration.h>


/* Owner package header include                             */
#include <AnsiCLibrary/Pkg_AnsiCLibrary.h>





 

/************************************************************/
/**
 * 
 */
class Class3
 {
  public:
	
	
	
  protected:
	
  private:
	

  public:

 	/**
 	 * 
 	 * @param arg 
 	 */
 	void  Operation1(int /*in*/ arg[25]);


  protected:


  private:


};
/************************************************************/
/* External declarations (package visibility)               */


/************************************************************/


/* Inline functions                                         */



/************************************************************
              End of Class3 class header
 ************************************************************/

#endif