// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef TESTCDTINTEGRATION_CLASS4_H
#define TESTCDTINTEGRATION_CLASS4_H

/************************************************************
              Class4 class header
 ************************************************************/

/* Owner package header include                             */
#include <TestCDTintegration/Pkg_TestCDTintegration.h>






 

/************************************************************/
/**
 * 
 */
class Class4
 {
  public:
	
  protected:
	
  private:
	

  public:


  protected:


  private:


};
/************************************************************/
/* External declarations (package visibility)               */


/************************************************************/


/* Inline functions                                         */



/************************************************************
              End of Class4 class header
 ************************************************************/

#endif