<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="facet"
    nsURI="http://www.eclipse.org/EmfFacet/infra/facet/0.8.incubation" nsPrefix="facet">
  <eClassifiers xsi:type="ecore:EClass" name="Facet" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="context Facet inv: self.conditionQuery.scope->exists(e|self.extendedClass.isSuperTypeOf(self.superType))&#xD;&#xA;&#xD;&#xA;context Facet inv: self.conditionQuery.retrunType.name == &quot;EBoolean&quot;&#xD;&#xA;&#xD;&#xA;context Facet inv: self.eStructuralFeature.isKindOf(FacetStructuralFeature)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionQuery" eType="ecore:EClass platform:/plugin/org.eclipse.emf.facet.infra.query/model/query.ecore#//ModelQuery"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="facetSet" eType="#//FacetSet"
        changeable="false" volatile="true" transient="true" derived="true" eOpposite="#//FacetSet/facets"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FacetAttribute" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute #//FacetStructuralFeature">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="context FacetAttribute inv: self.valueQuery.type.isKindOf(EDataType)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FacetReference" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference #//FacetStructuralFeature">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="context FacetReference inv: self.valueQuery.type.isKindOf(EClass)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FacetStructuralFeature" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueQuery" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.facet.infra.query/model/query.ecore#//ModelQuery"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setQuery" eType="ecore:EClass platform:/plugin/org.eclipse.emf.facet.infra.query/model/query.ecore#//ModelQuery">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The set query has to have one parameter. This parameter will be used to send the new value of the derived structural feature."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FacetSet" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage">
    <eOperations name="getFacet" eType="#//Facet">
      <eParameters name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedPackage" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="facets" upperBound="-1"
        eType="#//Facet" changeable="false" volatile="true" transient="true" derived="true"
        eOpposite="#//Facet/facetSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shortcut" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oppositeReference" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
  </eClassifiers>
</ecore:EPackage>
