<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aspectsemantic" nsURI="http://www.eclipse.org/papyrus/infra/extendedtypes/semantic/aspect/1.0"
    nsPrefix="aspectsemantic">
  <eClassifiers xsi:type="ecore:EClass" name="AspectSemanticTypeConfiguration" eSuperTypes="ExtendedTypes.ecore#//SemanticTypeConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adviceConfiguration" lowerBound="1"
        eType="#//AspectSemanticTypeAdviceConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AspectSemanticTypeAdviceConfiguration"
      eSuperTypes="ExtendedTypes.ecore#//SemanticTypeAdviceConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preActionConfiguration"
        upperBound="-1" eType="ecore:EClass ExtendedTypes.ecore#//SemanticActionConfiguration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postActionConfiguration"
        upperBound="-1" eType="ecore:EClass ExtendedTypes.ecore#//SemanticActionConfiguration"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
