<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aspectviewtypeconfiguration" nsURI="http://www.eclipse.org/papyrus/infra/extendedtypes/viewtype/aspect/1.0"
    nsPrefix="aspectviewtypeconfiguration">
  <eClassifiers xsi:type="ecore:EClass" name="AspectViewTypeConfiguration" eSuperTypes="ExtendedTypes.ecore#//ViewTypeConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preActionConfiguration"
        upperBound="-1" eType="ecore:EClass ExtendedTypes.ecore#//ViewActionConfiguration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postActionConfiguration"
        upperBound="-1" eType="ecore:EClass ExtendedTypes.ecore#//ViewActionConfiguration"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
