<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="querybasedmatcherconfiguration" nsURI="http://www.eclipse.org/papyrus/infra/extendedtypes/matcher/querybased/1.0"
    nsPrefix="querybasedmatcherconfiguration">
  <eClassifiers xsi:type="ecore:EClass" name="QueryBasedMatcherConfiguration" eSuperTypes="ExtendedTypes.ecore#//MatcherConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryConfiguration" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.papyrus.infra.queries.core.configuration/model/Configuration.ecore#//QueryConfiguration"/>
  </eClassifiers>
</ecore:EPackage>
