<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vSL"
    nsURI="http://www.eclipse.org/papyrus/marte/vsl/VSL" nsPrefix="vSL">
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ValueSpecification">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//AndOrXorExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndOrXorExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//EqualityExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EqualityExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//RelationalExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ConditionalExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//AdditiveExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//MultiplicativeExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicativeExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//UnaryExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unary" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//UnaryExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//PrimaryExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prefix" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ValueSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//SuffixExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuffixExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//SuffixExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyCallExpression" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//SuffixExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationCallExpression" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//SuffixExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ListOfValues"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ValueSpecification">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameOrChoiceOrBehaviorCall" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ValueSpecification">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//QualifiedName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ListOfValues"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedName">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Namespace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="remaining" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//QualifiedName"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interval" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ValueSpecification">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLowerIncluded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lower" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upper" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUpperIncluded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionOrTuple" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ValueSpecification">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listOfValues" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ListOfValues"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tuple" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ValueSpecification">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listOfValueNamePairs" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ListOfValueNamePairs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListOfValues">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListOfValueNamePairs">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueNamePairs" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ValueNamePair"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueNamePair">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeExpression" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ValueSpecification">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstantObsExpression" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//TimeExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//InstantObsName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstantObsName">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//QualifiedName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instantId" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//TimeObservation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DurationObsExpression" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//TimeExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//DurationObsName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DurationObsName">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//QualifiedName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="durationId" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//DurationObservation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JitterExp" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//TimeExpression">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstInstant" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//InstantObsExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondInstant" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//InstantObsExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//ValueSpecification">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableDeclaration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//DataTypeName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initValue" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeName">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//QualifiedName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteralRule" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Literal">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteralRule" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//NumberLiteralRule">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnlimitedLiteralRule" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//NumberLiteralRule">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealLiteralRule" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//NumberLiteralRule">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeLiteralRule" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Literal">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteralRule" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Literal">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullLiteralRule" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Literal">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultLiteralRule" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Literal">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteralRule" eSuperTypes="platform:/resource/org.eclipse.papyrus.marte.vsl/src-gen/org/eclipse/papyrus/marte/vsl/VSL.ecore#//Literal">
    <eOperations name="getFilteredParentRule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getFilteredParentRule(this, filter) ;"/>
      </eAnnotations>
      <eParameters name="filter" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getExpectedType" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getExpectedType(this) ;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getContextElement" eType="ecore:EClass platform:/resource/org.eclipse.papyrus.marte.vsl/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.papyrus.marte.vsl.extensions.VSLContextUtil.getContextElement(this) ;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
