
/*
 * generated by Xtext
 */
 
package org.eclipse.papyrus.transition.editor.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class UmlTransitionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipse.papyrus.transition.editor.xtext.ui.internal.UmlTransitionActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclipse.papyrus.transition.editor.xtext.ui.internal.UmlTransitionActivator.getInstance().getInjector("org.eclipse.papyrus.transition.editor.xtext.UmlTransition");
	}
	
}
