<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="umlState"
    nsURI="http://www.eclipse.org/papyrus/state/editor/xtext/UmlState" nsPrefix="umlState">
  <eClassifiers xsi:type="ecore:EClass" name="StateRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="#//EntryRule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="do" eType="#//DoRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exit" eType="#//ExitRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntryRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//BehaviorKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behaviorName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//BehaviorKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behaviorName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExitRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//BehaviorKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behaviorName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BehaviorKind">
    <eLiterals name="ACTIVITY" literal="Activity"/>
    <eLiterals name="STATE_MACHINE" value="1" literal="StateMachine"/>
    <eLiterals name="OPAQUE_BEHAVIOR" value="2" literal="OpaqueBehavior"/>
  </eClassifiers>
</ecore:EPackage>
