<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uml_diff_extension" nsURI="http://www.eclipse.org/papyrus/uml/compare/diff_ext/0.9"
    nsPrefix="uml_diff_extension">
  <eClassifiers xsi:type="ecore:EClass" name="GeneralizationTargetChangedExtension"
      eSuperTypes="#//UMLDiffExtension platform:/plugin/org.eclipse.emf.compare.diff/model/diff.ecore#//UpdateReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralizationSourceChangedExtension"
      eSuperTypes="#//UMLDiffExtension platform:/plugin/org.eclipse.emf.compare.diff/model/diff.ecore#//MoveModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UMLDiffExtension" eSuperTypes="platform:/plugin/org.eclipse.emf.compare.diff/model/diff.ecore#//AbstractDiffExtension"/>
</ecore:EPackage>
