<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nattable" nsURI="http://www.eclipse.org/papyrus/nattable/model"
    nsPrefix="nattable">
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//nattableconfiguration/TableNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableConfiguration" lowerBound="1"
        eType="#//nattableconfiguration/TableConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invertAxis" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnAxisProvidersHistory"
        lowerBound="1" upperBound="-1" eType="#//nattableaxisprovider/AbstractAxisProvider"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rowAxisProvidersHistory"
        lowerBound="1" upperBound="-1" eType="#//nattableaxisprovider/AbstractAxisProvider"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localRowHeaderAxisConfiguration"
        eType="#//nattableaxisconfiguration/LocalTableHeaderAxisConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localColumnHeaderAxisConfiguration"
        eType="#//nattableaxisconfiguration/LocalTableHeaderAxisConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentRowAxisProvider"
        lowerBound="1" eType="#//nattableaxisprovider/AbstractAxisProvider"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentColumnAxisProvider"
        lowerBound="1" eType="#//nattableaxisprovider/AbstractAxisProvider"/>
  </eClassifiers>
  <eSubpackages name="nattableconfiguration" nsURI="http://www.eclipse.org/papyrus/nattable/model/nattableconfiguration"
      nsPrefix="nattableconfiguration">
    <eClassifiers xsi:type="ecore:EClass" name="TableNamedElement" abstract="true"
        eSuperTypes="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TableConfiguration" eSuperTypes="#//nattableconfiguration/TableNamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconPath" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="creationTester" eType="#//nattabletester/AbstractTableTester"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cellEditorDeclaration"
          lowerBound="1" eType="#//nattableconfiguration/CellEditorDeclaration" defaultValueLiteral="COLUMN"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rowHeaderAxisConfiguration"
          lowerBound="1" eType="#//nattableaxisconfiguration/TableHeaderAxisConfiguration"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="columnHeaderAxisConfiguration"
          lowerBound="1" eType="#//nattableaxisconfiguration/TableHeaderAxisConfiguration"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="columnAxisProviders"
          lowerBound="1" upperBound="-1" eType="#//nattableaxisprovider/AbstractAxisProvider"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rowAxisProviders" lowerBound="1"
          upperBound="-1" eType="#//nattableaxisprovider/AbstractAxisProvider" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultRowAxisProvider"
          lowerBound="1" eType="#//nattableaxisprovider/AbstractAxisProvider"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultColumnAxisProvider"
          lowerBound="1" eType="#//nattableaxisprovider/AbstractAxisProvider"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CellEditorDeclaration">
      <eLiterals name="COLUMN"/>
      <eLiterals name="ROW" value="1"/>
      <eLiterals name="CELL" value="2"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="nattableaxisprovider" nsURI="http://www.eclipse.org/papyrus/nattable/model/table/nattableaxisprovider"
      nsPrefix="nattableaxisprovider">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractAxisProvider" abstract="true"
        eSuperTypes="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement #//nattableconfiguration/TableNamedElement">
      <eOperations name="getAxis" upperBound="-1" eType="#//nattableaxis/IAxis"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IMasterAxisProvider" abstract="true"
        interface="true" eSuperTypes="#//nattableaxisprovider/AxisProvider">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="disconnectSlave" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ISlaveAxisProvider" abstract="true"
        interface="true" eSuperTypes="#//nattableaxisprovider/AxisProvider"/>
    <eClassifiers xsi:type="ecore:EClass" name="AxisProvider" abstract="true" eSuperTypes="#//nattableaxisprovider/AbstractAxisProvider">
      <eStructuralFeatures xsi:type="ecore:EReference" name="axis" upperBound="-1"
          eType="#//nattableaxis/IAxis" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SlaveObjectAxisProvider" eSuperTypes="#//nattableaxisprovider/ISlaveAxisProvider"/>
    <eClassifiers xsi:type="ecore:EClass" name="MasterObjectAxisProvider" eSuperTypes="#//nattableaxisprovider/IMasterAxisProvider"/>
  </eSubpackages>
  <eSubpackages name="nattablelabelprovider" nsURI="http://www.eclipse.org/papyrus/nattable/model/table/nattablecontentprovider"
      nsPrefix="nattablelabelprovider">
    <eClassifiers xsi:type="ecore:EClass" name="ILabelProviderConfiguration" abstract="true"
        interface="true" eSuperTypes="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureLabelProviderConfiguration"
        eSuperTypes="#//nattablelabelprovider/ObjectLabelProviderConfiguration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayIsDerived" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayType" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayMultiplicity"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectLabelProviderConfiguration"
        eSuperTypes="#//nattablelabelprovider/ILabelProviderConfiguration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayIcon" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayLabel" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="nattableaxisconfiguration" nsURI="http://www.eclipse.org/papyrus/nattable/model/table/nattableaxisconfiguration"
      nsPrefix="nattableaxisconfiguration">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractHeaderAxisConfiguration" abstract="true"
        eSuperTypes="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexStyle" lowerBound="1"
          eType="#//nattableaxisconfiguration/AxisIndexStyle"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayLabel" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayFilter" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayIndex" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLabelConfiguration"
          upperBound="-1" eType="#//nattablelabelprovider/ILabelProviderConfiguration"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAxisConfiguration"
          upperBound="-1" eType="#//nattableaxisconfiguration/IAxisConfiguration"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AxisManagerRepresentation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="axisManagerId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelProviderContext"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="headerLabelConfiguration"
          lowerBound="1" eType="#//nattablelabelprovider/ILabelProviderConfiguration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specificAxisConfigurations"
          upperBound="-1" eType="#//nattableaxisconfiguration/IAxisConfiguration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AxisManagerConfiguration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="localHeaderLabelConfiguration"
          eType="#//nattablelabelprovider/ILabelProviderConfiguration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="axisManager" lowerBound="1"
          eType="#//nattableaxisconfiguration/AxisManagerRepresentation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="localSpecificConfigurations"
          upperBound="-1" eType="#//nattableaxisconfiguration/IAxisConfiguration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TableHeaderAxisConfiguration" eSuperTypes="#//nattableaxisconfiguration/AbstractHeaderAxisConfiguration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="axisManagers" lowerBound="1"
          upperBound="-1" eType="#//nattableaxisconfiguration/AxisManagerRepresentation"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LocalTableHeaderAxisConfiguration"
        eSuperTypes="#//nattableaxisconfiguration/AbstractHeaderAxisConfiguration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="axisManagerConfigurations"
          upperBound="-1" eType="#//nattableaxisconfiguration/AxisManagerConfiguration"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IAxisConfiguration" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureAxisConfiguration" eSuperTypes="#//nattableaxisconfiguration/IAxisConfiguration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="showOnlyCommonFeature"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IFillingConfiguration" abstract="true"
        interface="true" eSuperTypes="#//nattableaxisconfiguration/IAxisConfiguration"/>
    <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeatureValueFillingConfiguration"
        eSuperTypes="#//nattableaxisconfiguration/IFillingConfiguration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="listenFeature" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IPasteConfiguration" eSuperTypes="#//nattableaxisconfiguration/IAxisConfiguration"/>
    <eClassifiers xsi:type="ecore:EClass" name="PasteEObjectConfiguration" eSuperTypes="#//nattableaxisconfiguration/IPasteConfiguration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pastedElementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pasteElementContainementFeature"
          eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AxisIndexStyle">
      <eLiterals name="ALPHABETIC" value="1" literal="ALPHABETIC"/>
      <eLiterals name="NUMERIC" literal="NUMERIC"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="nattabletester" nsURI="http://www.eclipse.org/papyrus/nattable/model/table/nattabletester"
      nsPrefix="nattabletester">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractTableTester" abstract="true"
        eSuperTypes="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
      <eOperations name="getTester" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JavaTableTester" eSuperTypes="#//nattabletester/AbstractTableTester">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tester" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="nattableaxis" nsURI="http://www.eclipse.org/papyrus/nattable/model/table/nattableaxis"
      nsPrefix="nattableaxis">
    <eClassifiers xsi:type="ecore:EClass" name="IAxis" abstract="true" interface="true">
      <eOperations name="getElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eOperations name="getLocalLabelConfiguration" eType="#//nattablelabelprovider/ILabelProviderConfiguration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="manager" lowerBound="1"
          eType="#//nattableaxisconfiguration/AxisManagerRepresentation"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IdAxis" abstract="true" eSuperTypes="#//nattableaxis/IAxis">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="element" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EObjectAxis" eSuperTypes="#//nattableaxis/ObjectAxis">
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureAxis" abstract="true" eSuperTypes="#//nattableaxis/IAxis">
      <eStructuralFeatures xsi:type="ecore:EReference" name="localLabelConfiguration"
          eType="#//nattablelabelprovider/FeatureLabelProviderConfiguration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectAxis" abstract="true" eSuperTypes="#//nattableaxis/IAxis">
      <eStructuralFeatures xsi:type="ecore:EReference" name="localLabelConfiguration"
          eType="#//nattablelabelprovider/ObjectLabelProviderConfiguration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureIdAxis" eSuperTypes="#//nattableaxis/IdAxis #//nattableaxis/FeatureAxis"/>
    <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeatureAxis" eSuperTypes="#//nattableaxis/FeatureAxis">
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
          eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectIdAxis" eSuperTypes="#//nattableaxis/IdAxis #//nattableaxis/ObjectAxis"/>
  </eSubpackages>
</ecore:EPackage>
