<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nattableconfiguration" nsURI="http://www.eclipse.org/papyrus/nattableconfiguration/model"
    nsPrefix="nattableconfiguration">
  <eClassifiers xsi:type="ecore:EClass" name="TableEditorConfiguration" eSuperTypes="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pastedElementTypeId" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pastedElementContainmentFeature"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalTableEditorConfiguration" eSuperTypes="#//TableEditorConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultTableEditorConfiguration"
        eType="#//TableEditorConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
