/*
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.textedit.connectionpointreference.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UMLConnectionPointReferenceUiModule extends org.eclipse.papyrus.uml.textedit.connectionpointreference.xtext.ui.AbstractUMLConnectionPointReferenceUiModule {
	public UMLConnectionPointReferenceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
