/*
 * generated by Xtext
 */
package org.eclipse.papyrus.marte.textedit.constraintwithvsl.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.papyrus.marte.textedit.constraintwithvsl.xtext.ui.internal.ConstraintWithVSLlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConstraintWithVSLlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ConstraintWithVSLlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ConstraintWithVSLlActivator.getInstance().getInjector(ConstraintWithVSLlActivator.ORG_ECLIPSE_PAPYRUS_MARTE_TEXTEDIT_CONSTRAINTWITHVSL_XTEXT_CONSTRAINTWITHVSLL);
	}
	
}
