grammar org.eclipse.papyrus.constraintwithvsl.editor.xtext.ConstraintWithVSLl 
//with org.eclipse.xtext.common.Terminals
with org.eclipse.papyrus.marte.vsl.VSL

import "http://www.eclipse.org/uml2/3.0.0/UML" as uml

generate constraintWithVSLl "http://www.eclipse.org/papyrus/constraintwithvsl/editor/xtext/ConstraintWithVSLl"

ConstraintRule :
	(specification = ConstraintSpecification)? ;
	
ConstraintSpecification :
	expression = Expression ;
