/*
* generated by Xtext
*/
package org.eclipse.papyrus.stereotypeapplicationwithvsl.editor.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class StereotypeApplicationWithVSLTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
