/*
 * generated by Xtext
 */
package org.eclipse.papyrus.transition.editor.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UmlTransitionRuntimeModule extends org.eclipse.papyrus.transition.editor.xtext.AbstractUmlTransitionRuntimeModule {

}
