/*
 * generated by Xtext
 */
package org.eclipse.papyrus.constraintwithvsl.editor.xtext.scoping;

import org.eclipse.papyrus.marte.vsl.scoping.VSLScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class ConstraintWithVSLlScopeProvider extends VSLScopeProvider {

}
