package org.eclipse.papyrus.infra.table.efacet.menu.handler;


//TODO merge with the same class in oep.uml.efacet
public class Constants {

	
	private Constants() {
		//to prevent instanciation
	}
	
	public static final String STEREOTYPE_QUALIFIED_NAME = "stereotypeQualifiedName";
	public static final String STEREOTYPE_PROPERTY_NAME = "stereotypePropertyName";
	
	public static final String ADDITIONAL_CONTENTS_FACET_SET_NAME = "AdditionalContentsForTable";

	public static final String ADDITIONAL_CONTENTS_FACET_SET_NS_URI = "http://www.eclipse.org/papyrustableefacet/additionalcontentsfacetset";

	public static final String ADDITIONAL_CONTENTS_FACET_SET_PREFIX = "additionalcontentsfacetset";

	public static final String ADDITIONAL_CONTENTS_FACET_SET_DOCUMENTATION = "This FacetSet provides facets to edit easily additional contents (as Stereotype Properties). It had been generated by the Papyrus Show/Hide columns";
}
