<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uml_diff_extension"
    nsURI="http://www.eclipse.org/uml/compare/diff_ext/1.0" nsPrefix="uml_diff_extension">
  <eClassifiers xsi:type="ecore:EClass" name="UMLDiffExtension" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.compare.diff/model/diff.ecore#//AbstractDiffExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="StereotypeChange" eSuperTypes="#//UMLDiffExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="TaggedValueChange" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.compare.diff/model/diff.ecore#//AttributeChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="TaggedValueChangeLeftTarget" eSuperTypes="platform:/plugin/org.eclipse.emf.compare.diff/model/diff.ecore#//AttributeChangeLeftTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="TaggedValueChangeRightTarget" eSuperTypes="platform:/plugin/org.eclipse.emf.compare.diff/model/diff.ecore#//AttributeChangeRightTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateTaggedValue" eSuperTypes="platform:/plugin/org.eclipse.emf.compare.diff/model/diff.ecore#//UpdateAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddStereotypeApplication" eSuperTypes="#//StereotypeChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveStereotypeApplication" eSuperTypes="#//StereotypeChange"/>
</ecore:EPackage>
