/*
* generated by Xtext
*/
package org.eclipse.papyrus.alf.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class AlfOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
