<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="defaultname" nsURI="http://defaultname/1.0" nsPrefix="defaultname">
  <eAnnotations source="récupérer en utilisant le catalogue"/>
  <eAnnotations source="récupérer en utilisant le catalogue" references="#//uml.nattable.generic/vaChercher #//sysml.nattable.allocation/vaChercher"/>
  <eAnnotations source="fourni la contribution aux menus" references="#//uml.nattable.generic #//sysml.nattable.allocation"/>
  <eAnnotations source="fourni tout ce qui est dans le catalogue" references="#//futurWizard"/>
  <eClassifiers xsi:type="ecore:EClass" name="catalogue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" upperBound="-1"
        eType="#//TableConfig"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableConfig">
    <eStructuralFeatures xsi:type="ecore:EReference" name="utilisé par " upperBound="-1"
        eType="#//EditorPlugins"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLNattableConfig">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contribue" upperBound="-1"
        eType="#//catalogue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="UMLGenericTableConfig"
        lowerBound="1" eType="#//TableConfig" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SysMLNattableConfig">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contribue" upperBound="-1"
        eType="#//catalogue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SysMLTableConfig" lowerBound="1"
        eType="#//TableConfig" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SysmlAllocationConfig"
        lowerBound="1" eType="#//TableConfig" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uml.nattable.generic" eSuperTypes="#//EditorPlugins">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vaChercher" lowerBound="1"
        eType="#//catalogue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="sysml.nattable.allocation" eSuperTypes="#//EditorPlugins">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vaChercher" lowerBound="1"
        eType="#//catalogue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="futurWizard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" lowerBound="1"
        eType="#//catalogue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditorPlugins"/>
</ecore:EPackage>
