/*
* generated by Xtext
*/
package org.eclipse.papyrus.uml.textedit.connectionpointreference.xtext.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class UMLConnectionPointReferenceProposalProvider extends AbstractUMLConnectionPointReferenceProposalProvider {

}
